[package]
name = "nostr-grpc"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Nostr GRPC types"
repository = "https://github.com/illuminodes/nostr-grpc"
readme = "README.md"
homepage = "https://github.com/illuminodes/nostr-grpc"

[build-dependencies]
tonic-build = "0.12.1"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
nostro2 = "0.2.4"
tokio = { version = "1.43.0", features = ["sync", "macros"] }

tonic-web = "0.12.1"
prost = "0.13.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tonic = { version = "0.12.1", features = ["prost", "codegen", "channel"]}

[target.'cfg(target_arch = "wasm32")'.dependencies]
tonic = { version = "0.12.1", features = ["prost", "codegen"], default-features = false }
tonic-web-wasm-client = "0.6.0"

