// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Empty {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LoginRole {
    #[prost(bool, tag = "1")]
    pub is_admin: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GrpcNostrNoteId {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GrpcNostrNoteTag {
    #[prost(string, repeated, tag = "1")]
    pub tag: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GrpcNostrNote {
    #[prost(string, tag = "1")]
    pub content: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub kind: u32,
    #[prost(string, tag = "3")]
    pub pubkey: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub created_at: i64,
    #[prost(message, repeated, tag = "5")]
    pub tags: ::prost::alloc::vec::Vec<GrpcNostrNoteTag>,
    #[prost(string, tag = "6")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub sig: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GrpcNostrNoteList {
    #[prost(message, repeated, tag = "1")]
    pub events: ::prost::alloc::vec::Vec<GrpcNostrNote>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Filter {
    #[prost(string, repeated, tag = "1")]
    pub authors: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint32, repeated, tag = "2")]
    pub kinds: ::prost::alloc::vec::Vec<u32>,
    #[prost(string, repeated, tag = "3")]
    pub ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint32, tag = "4")]
    pub since: u32,
    #[prost(uint32, tag = "5")]
    pub until: u32,
    #[prost(uint32, tag = "6")]
    pub limit: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FilterTag {
    #[prost(string, repeated, tag = "1")]
    pub parameter: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
